# Numpy : numerical python (numeric computing python)

NumPy (Numerical Python) is one of the core packages for numerical computing in Python. Pandas, Matplotlib, Statmodels and many other Scientific libraries rely on NumPy.
 

In [42]:
import numpy as np

In [43]:
a = np.array([1,2,3,4,5])
b = np.array([.2,.3,4.5])

In [44]:
a

array([1, 2, 3, 4, 5])

In [45]:
a.dtype
b.dtype

dtype('float64')

In [46]:
a[[0,2,1]]

array([1, 3, 2])

In [47]:
c = np.array([
    [1,2,3],
    [4,5,6]
])

In [48]:
c.ndim

2

In [49]:
c.size

6

In [50]:
c.shape

(2, 3)

In [51]:
c[1][0]

4

In [52]:
c[1,0]

4

In [53]:
c[0] = np.array([10,10,10])

In [54]:
c

array([[10, 10, 10],
       [ 4,  5,  6]])

In [55]:
c[1] = 99

In [56]:
c

array([[10, 10, 10],
       [99, 99, 99]])

In [57]:
a = np.array([1,2,3,4,5])

In [58]:
a.sum()

15

In [59]:
a.mean()

3.0

In [60]:
a.var()

2.0

In [61]:
a = np.arange(5)

In [62]:
a

array([0, 1, 2, 3, 4])

In [63]:
a + 10

array([10, 11, 12, 13, 14])

In [64]:
a = np.array([
    [0,1,2],
    [3,4,5],
    [6,7,8]
])

In [71]:
a.max()

8

In [68]:
print(type(list(a.mean(axis=0))))

<class 'list'>
